version: "3.7"
name: genarchi-dev
services:
  database:
    image: postgres
    volumes:
      - 'postgres:/var/lib/postgresql/data:rw'
      - ./scripts/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: "${DATABASE_NAME}"
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    ports:
      - '8208:8208'
    command: -p 8208

volumes:
  postgres:
    driver: local
