@startuml

'class Vin {
'    id: Serial
'    couleur: String
'    domaine: String
'    nom: String
'    millesime: Integer
'    apogee: Integer
'}
'
'
'class Caisse {
'    id: Serial
'    id_vin: Serial
'    nombre: Integer
'}

class Quote {
    id: Serial
    text: String
    likes: Integer
    author: String
}

@enduml