version: "3.7"
name: genarchi-backend
services:
  backend:
    build: .
    restart: always
    ports:
      - '${PORT}:${PORT}'
    environment:
      DATABASE_URL: "postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@database:8208"
      SESSION_SECRET: "${SESSION_SECRET}"
      NODE_ENV: "${NODE_ENV}"
    depends_on:
      - database

  database:
    image: postgres:14.2-alpine
    volumes:
      - 'postgres:/var/lib/postgresql/data:rw'
      - ./scripts/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: "${DATABASE_NAME}"
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    ports:
      - '8208:8208'
    command: -p 8208

volumes:
  postgres:
    driver: local
